# VLESS + WS + TLS - Go parity, paling populer untuk VLESS

[[vless]]
addr = "1.2.3.4:443"
uuid = "b831381d-6324-4d53-ad4f-8cda48b30811"
tag = "vless"

[[ws]]
uri = "wss://example.com:443/ws?ed=2048"
tag = "ws"

[[tls]]
sni = "example.com"
tag = "tls"

[[direct]]
tag = "direct"

[[outbounds]]
chain = ["tls", "ws", "vless"]
tag = "proxy"

[[outbounds]]
chain = ["direct"]
tag = "direct-out"

[[inbounds]]
addr = "127.0.0.1:1080"
enable_udp = true
tag = "socks"

[[inbounds]]
addr = "127.0.0.1:1081"
tag = "http"
