# VMess + HTTP/2 + TLS - Go parity

[[vmess]]
addr = "1.2.3.4:443"
uuid = "b831381d-6324-4d53-ad4f-8cda48b30811"
method = "aes-128-gcm"
tag = "vmess"

[[h2]]
hosts = ["example.com"]
path = "/ray"
# method default GET, bisa POST
# headers opsional
tag = "h2"

[[tls]]
sni = "example.com"
tag = "tls"

[[direct]]
tag = "direct"

[[outbounds]]
chain = ["tls", "h2", "vmess"]
tag = "proxy"

[[outbounds]]
chain = ["direct"]
tag = "direct-out"

[[inbounds]]
addr = "127.0.0.1:1080"
enable_udp = true
tag = "socks"
